import type { Knex } from 'knex';

/**
 * JGN clinical-chemistry catalog import. Sourced from jgn-items.xlsx
 * (sheet: 'clinical chemistry'). Generated by _tmp_xlsx/build_mapping.py
 * — regenerate rather than editing this file by hand.
 *
 * Duplicate itemcodes in the source (CC014/015/016 reused twice) were
 * renumbered: PHOSPHORUS → CC021, ALKALINE PHOSPHATASE → CC022,
 * BILIRUBIN → CC023.
 *
 * Runs via env vars so the same seed can target any tenant + category:
 *   JGN_TENANT_UUID=<uuid> JGN_CATEGORY_UUID=<uuid> \
 *     npx knex seed:run --specific 08_seed_jgn_chemistry.ts
 *
 * Also exported as seedJgnChemistry(knex, opts) for direct calls from
 * scripts or other seeds.
 *
 * Idempotent — checks (tenant_uuid, code) before inserting; components
 * checked by (test_item_uuid, code). Existing rows are left untouched.
 */

type ResultType = 'single' | 'panel';

interface ComponentSeed {
	code: string;
	name: string;
	unit_of_measure: string | null;
	reference_range: string | null;
	si_conversion_factor: number | null;
	si_unit_of_measure: string | null;
	si_reference_range: string | null;
	display_order: number;
}

interface TestItemSeed {
	code: string;
	name: string;
	result_type: ResultType;
	price: number;
	unit_of_measure: string | null;
	reference_range: string | null;
	si_conversion_factor: number | null;
	si_unit_of_measure: string | null;
	si_reference_range: string | null;
	components: ComponentSeed[];
}

const ITEMS: TestItemSeed[] = [
	{
		code: 'CC001',
		name: 'FBS/RBS/2HPPBS',
		result_type: 'panel',
		price: 120,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: null,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [
			{
				code: 'CC001-01',
				name: 'Fasting',
				unit_of_measure: 'mg/dL',
				reference_range: '70-105 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: '3.89-5.83 mmol/L',
				display_order: 1,
			},
			{
				code: 'CC001-02',
				name: '2hPP',
				unit_of_measure: 'mg/dL',
				reference_range: 'up tp 150 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 8.25 mmol/L',
				display_order: 2,
			},
			{
				code: 'CC001-03',
				name: 'Random',
				unit_of_measure: null,
				reference_range: null,
				si_conversion_factor: 0.055,
				si_unit_of_measure: null,
				si_reference_range: null,
				display_order: 3,
			},
		],
	},
	{
		code: 'CC002',
		name: 'TOTAL CHOLESTEROL',
		result_type: 'single',
		price: 150,
		unit_of_measure: 'mg/dL',
		reference_range: 'up to 200 mg/dL',
		si_conversion_factor: 0.026,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: 'less than 5.2 mmol/L',
		components: [],
	},
	{
		code: 'CC003',
		name: 'LIPID PROFILE',
		result_type: 'panel',
		price: 650,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: null,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [
			{
				code: 'CC003-01',
				name: 'Cholesterol Total',
				unit_of_measure: 'mg/dL',
				reference_range: 'up-200 mg/dL',
				si_conversion_factor: 0.026,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 5.2 mmol/L',
				display_order: 1,
			},
			{
				code: 'CC003-02',
				name: 'Triglycerides',
				unit_of_measure: 'mg/dL',
				reference_range: 'up-160 mg/dL',
				si_conversion_factor: 0.0114,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 1.7 mmol/L',
				display_order: 2,
			},
			{
				code: 'CC003-03',
				name: 'HDL Cholesterol',
				unit_of_measure: 'mg/dL',
				reference_range: '40-60mg/dL',
				si_conversion_factor: 0.026,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: '1.04- 1.56 mmol/L',
				display_order: 3,
			},
			{
				code: 'CC003-04',
				name: 'LDL Cholesterol',
				unit_of_measure: 'mg/dL',
				reference_range: '0-130 mg/dL',
				si_conversion_factor: 0.026,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 3.38 mmol/L',
				display_order: 4,
			},
			{
				code: 'CC003-05',
				name: 'VLDL',
				unit_of_measure: 'mg/dL',
				reference_range: 'mg/dL',
				si_conversion_factor: null,
				si_unit_of_measure: null,
				si_reference_range: null,
				display_order: 5,
			},
		],
	},
	{
		code: 'CC004',
		name: 'TRIGLYCERIDES',
		result_type: 'single',
		price: 230,
		unit_of_measure: 'mg/d',
		reference_range: 'Up to 160 mg/d',
		si_conversion_factor: 0.0114,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: 'less than 1.7 mmol/L',
		components: [],
	},
	{
		code: 'CC005',
		name: 'CREATININE',
		result_type: 'single',
		price: 150,
		unit_of_measure: 'mg/dL',
		reference_range: 'F : 0.6-1.1 mg/dL; M :0.9-1.3 mg/dL',
		si_conversion_factor: 88.4,
		si_unit_of_measure: 'umol/L',
		si_reference_range: 'F: 53-97  umol/L; M:80-115 umol/L',
		components: [],
	},
	{
		code: 'CC006',
		name: 'BUN',
		result_type: 'single',
		price: 150,
		unit_of_measure: 'mg/dL',
		reference_range: '7-18 mg/dL',
		si_conversion_factor: 0.357,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '2.5-6.5 mmol/L',
		components: [],
	},
	{
		code: 'CC007',
		name: 'URIC ACID',
		result_type: 'single',
		price: 150,
		unit_of_measure: 'mg/dL',
		reference_range: 'F : 2.6-6.0 mg/dL; M :3-5-7.2 mg/dL',
		si_conversion_factor: 59.5,
		si_unit_of_measure: 'umol/L',
		si_reference_range: 'F: 150-350 umol/L; M:210-420 umol/L',
		components: [],
	},
	{
		code: 'CC008',
		name: 'SGPT',
		result_type: 'single',
		price: 230,
		unit_of_measure: 'U/L',
		reference_range: '0-41 U/L',
		si_conversion_factor: 1.0,
		si_unit_of_measure: 'U/L',
		si_reference_range: 'less than 41 U/L',
		components: [],
	},
	{
		code: 'CC009',
		name: 'SGOT',
		result_type: 'single',
		price: 230,
		unit_of_measure: 'U/L',
		reference_range: '0-40 U/L',
		si_conversion_factor: 1.0,
		si_unit_of_measure: 'U/L',
		si_reference_range: 'less than 40 U/L',
		components: [],
	},
	{
		code: 'CC010',
		name: 'SODIUM (Na+)',
		result_type: 'single',
		price: 250,
		unit_of_measure: 'meq/L',
		reference_range: '135-148 meq/L',
		si_conversion_factor: 1.0,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '135-148 mmol/L',
		components: [],
	},
	{
		code: 'CC011',
		name: 'POTASSIUM (K+)',
		result_type: 'single',
		price: 250,
		unit_of_measure: 'meq/L',
		reference_range: '3.7-5.3 meq/L',
		si_conversion_factor: 1.0,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '3.7-5.3 mmol/L',
		components: [],
	},
	{
		code: 'CC012',
		name: 'CALCIUM (Ca 2+)',
		result_type: 'single',
		price: 250,
		unit_of_measure: 'mg/dL',
		reference_range: '8.1-10.4 mg/dL',
		si_conversion_factor: 0.25,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '2.02-2.60 mmol/L',
		components: [],
	},
	{
		code: 'CC013',
		name: 'MAGNESIUM',
		result_type: 'single',
		price: 400,
		unit_of_measure: 'mg/dL',
		reference_range: '1.7-2.4 mg/dL',
		si_conversion_factor: 0.41,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '0.70-0.98 mmol/L',
		components: [],
	},
	{
		code: 'CC014',
		name: 'GLUCOSE TOLERANCE 50grams',
		result_type: 'single',
		price: 500,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: 0.055,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [],
	},
	{
		code: 'CC015',
		name: 'GLUCOSE TOLERANCE 75grams',
		result_type: 'panel',
		price: 750,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: null,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [
			{
				code: 'CC015-01',
				name: 'FASTING BLOOD SUGAR (GLUCOSE)',
				unit_of_measure: 'mg/dL',
				reference_range: '74-106 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: '3.89-5.83 mmol/L',
				display_order: 1,
			},
			{
				code: 'CC015-02',
				name: '1 HOUR OGTT',
				unit_of_measure: 'mg/dL',
				reference_range: '< 200 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 11 mmol/L',
				display_order: 2,
			},
			{
				code: 'CC015-03',
				name: '2 HOUR OGTT',
				unit_of_measure: 'mg/dL',
				reference_range: '< 140 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 7.7 mmol/L',
				display_order: 3,
			},
		],
	},
	{
		code: 'CC016',
		name: 'GLUCOSE TOLERANCE 100grams',
		result_type: 'panel',
		price: 850,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: null,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [
			{
				code: 'CC016-01',
				name: 'FASTING BLOOD SUGAR (GLUCOSE)',
				unit_of_measure: 'mg/dL',
				reference_range: '74-106 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: '3.89-5.83 mmol/L',
				display_order: 1,
			},
			{
				code: 'CC016-02',
				name: '1 HOUR OGTT',
				unit_of_measure: 'mg/dL',
				reference_range: '< 185 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 10.18 mmol/L',
				display_order: 2,
			},
			{
				code: 'CC016-03',
				name: '2 HOUR OGTT',
				unit_of_measure: 'mg/dL',
				reference_range: '< 155 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 85.25 mmol/L',
				display_order: 3,
			},
			{
				code: 'CC016-04',
				name: '3 HOUR OGTT',
				unit_of_measure: 'mg/dL',
				reference_range: '< 140 mg/dL',
				si_conversion_factor: 0.055,
				si_unit_of_measure: 'mmol/L',
				si_reference_range: 'less than 7.7 mmol/L',
				display_order: 4,
			},
		],
	},
	{
		code: 'CC021',
		name: 'PHOSPHORUS',
		result_type: 'single',
		price: 400,
		unit_of_measure: 'mg/dL',
		reference_range: '2.5-4.5 mg/dL',
		si_conversion_factor: 0.323,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '0.81-1.45 mmol/L',
		components: [],
	},
	{
		code: 'CC022',
		name: 'ALKALINE PHOSPHATASE',
		result_type: 'single',
		price: 400,
		unit_of_measure: 'U/L',
		reference_range: 'F : 0-105 U/L; M : 0-105 U/L',
		si_conversion_factor: 1.0,
		si_unit_of_measure: 'U/L',
		si_reference_range: '0-105 U/L',
		components: [],
	},
	{
		code: 'CC023',
		name: 'BILIRUBIN',
		result_type: 'panel',
		price: 400,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: null,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [
			{
				code: 'CC023-01',
				name: 'Total',
				unit_of_measure: 'mg/dL',
				reference_range: '0-1.125 mg/dL',
				si_conversion_factor: 17.1,
				si_unit_of_measure: 'umol/L',
				si_reference_range: 'up to 17 umol/L',
				display_order: 1,
			},
			{
				code: 'CC023-02',
				name: 'Direct',
				unit_of_measure: 'mg/dL',
				reference_range: '0-0.25 mg/dL',
				si_conversion_factor: 17.1,
				si_unit_of_measure: 'umol/L',
				si_reference_range: 'up to 4.3 umol/L',
				display_order: 2,
			},
			{
				code: 'CC023-03',
				name: 'Indirect',
				unit_of_measure: 'mg/dL',
				reference_range: '0-0.85 mg/dL',
				si_conversion_factor: 17.1,
				si_unit_of_measure: 'umol/L',
				si_reference_range: 'up to 14.54 umol/L',
				display_order: 3,
			},
		],
	},
	{
		code: 'CC017',
		name: 'ALBUMIN',
		result_type: 'single',
		price: 250,
		unit_of_measure: 'g/dL',
		reference_range: '3.8-5.15g/dL',
		si_conversion_factor: 10.0,
		si_unit_of_measure: 'g/L',
		si_reference_range: '38-51 g/L',
		components: [],
	},
	{
		code: 'CC018',
		name: 'CHLORIDE',
		result_type: 'single',
		price: 250,
		unit_of_measure: 'meq/L',
		reference_range: '98-109 meq/L',
		si_conversion_factor: 1.0,
		si_unit_of_measure: 'mmol/L',
		si_reference_range: '98-109 mmol/L',
		components: [],
	},
	{
		code: 'CC019',
		name: 'LACTATE DEHYDROGENASE',
		result_type: 'single',
		price: 400,
		unit_of_measure: 'uL',
		reference_range: '207-414 uL',
		si_conversion_factor: null,
		si_unit_of_measure: 'uL',
		si_reference_range: '207-414 uL',
		components: [],
	},
	{
		code: 'CC020',
		name: 'TPAG',
		result_type: 'panel',
		price: 500,
		unit_of_measure: null,
		reference_range: null,
		si_conversion_factor: null,
		si_unit_of_measure: null,
		si_reference_range: null,
		components: [
			{
				code: 'CC020-01',
				name: 'Total Protein',
				unit_of_measure: 'g/L',
				reference_range: '64-83 g/L',
				si_conversion_factor: null,
				si_unit_of_measure: null,
				si_reference_range: null,
				display_order: 1,
			},
			{
				code: 'CC020-02',
				name: 'Albumin',
				unit_of_measure: 'g/L',
				reference_range: '35-50 g/L',
				si_conversion_factor: null,
				si_unit_of_measure: null,
				si_reference_range: null,
				display_order: 2,
			},
			{
				code: 'CC020-03',
				name: 'Globulin',
				unit_of_measure: 'g/L',
				reference_range: '29-34 g/L',
				si_conversion_factor: null,
				si_unit_of_measure: null,
				si_reference_range: null,
				display_order: 3,
			},
			{
				code: 'CC020-04',
				name: 'Albumin:Globulin Ratio',
				unit_of_measure: 'g/L',
				reference_range: '1.3-3.0:1 g/L',
				si_conversion_factor: null,
				si_unit_of_measure: null,
				si_reference_range: null,
				display_order: 4,
			},
		],
	},
];

export interface SeedJgnChemistryOptions {
	tenant_uuid: string;
	item_category_uuid: string;
	created_by?: string;
}

export interface SeedJgnChemistryResult {
	items_inserted: number;
	items_skipped: number;
	components_inserted: number;
}

export async function seedJgnChemistry(
	knex: Knex,
	opts: SeedJgnChemistryOptions,
): Promise<SeedJgnChemistryResult> {
	const { tenant_uuid, item_category_uuid } = opts;
	const created_by = opts.created_by ?? 'seed:08_seed_jgn_chemistry';
	let items_inserted = 0;
	let items_skipped = 0;
	let components_inserted = 0;

	for (const item of ITEMS) {
		let row = await knex('test_items')
			.where({ tenant_uuid, code: item.code })
			.first();
		if (row) {
			items_skipped += 1;
		} else {
			const [inserted] = await knex('test_items')
				.insert({
					tenant_uuid,
					item_category_uuid,
					code: item.code,
					name: item.name,
					result_type: item.result_type,
					unit_of_measure: item.unit_of_measure,
					reference_range: item.reference_range,
					si_conversion_factor: item.si_conversion_factor,
					si_unit_of_measure: item.si_unit_of_measure,
					si_reference_range: item.si_reference_range,
					price: item.price,
					status: 'active',
					created_by,
				})
				.returning('*');
			row = inserted;
			items_inserted += 1;
		}

		if (item.result_type === 'panel' && item.components.length) {
			for (const c of item.components) {
				const exists = await knex('test_item_components')
					.where({ test_item_uuid: row.uuid, code: c.code })
					.first();
				if (exists) continue;
				await knex('test_item_components').insert({
					tenant_uuid,
					test_item_uuid: row.uuid,
					code: c.code,
					name: c.name,
					unit_of_measure: c.unit_of_measure,
					reference_range: c.reference_range,
					si_conversion_factor: c.si_conversion_factor,
					si_unit_of_measure: c.si_unit_of_measure,
					si_reference_range: c.si_reference_range,
					display_order: c.display_order,
					created_by,
				});
				components_inserted += 1;
			}
		}
	}

	return { items_inserted, items_skipped, components_inserted };
}

export async function seed(knex: Knex): Promise<void> {
	const tenant_uuid = process.env.JGN_TENANT_UUID;
	const item_category_uuid = process.env.JGN_CATEGORY_UUID;
	if (!tenant_uuid || !item_category_uuid) {
		// eslint-disable-next-line no-console
		console.warn(
			'[seed 08] Skipped — set JGN_TENANT_UUID and JGN_CATEGORY_UUID env vars, ' +
				'or import seedJgnChemistry() and call it directly with your ids.',
		);
		return;
	}
	const result = await seedJgnChemistry(knex, { tenant_uuid, item_category_uuid });
	// eslint-disable-next-line no-console
	console.log(
		`[seed 08] Items inserted=${result.items_inserted} skipped=${result.items_skipped}, ` +
			`components inserted=${result.components_inserted}`,
	);
}
