import type { Knex } from 'knex';

/**
 * JGN serology catalog import. Sourced from jgn-items.xlsx
 * (sheet: 'serology'). Generated by _tmp_xlsx/build_mapping_serology.py
 * — regenerate rather than editing this file by hand.
 *
 * Renames applied to keep test_items.code unique per tenant:
 *   - CARCINOEMBRYONIC ANTIGEN (CEA)  ST018 → ST023 (dupe with β-HCG)
 *   - IONIZED CALCIUM                 CC022 → SS010 (cross-sheet collision
 *     with chemistry ALKALINE PHOSPHATASE + wrong prefix for serology)
 *   - β-HCG name: mojibake cleanup
 *
 * Result-type notes:
 *   - Almost every item is a `single`. Reference range comes from the
 *     'Normal Value' / 'REFERENCE VALUE:' row when present; lookup_values
 *     from the 'RESULT' row when the source lists semicolon-separated
 *     picks like 'Reactive;Non-Reactive'.
 *   - Salmonella typhi IgG/IgM is the one true panel (explicit IgG + IgM
 *     rows in the source).
 *   - No SI columns on this sheet, so si_* fields stay null.
 *
 * Runs via env vars:
 *   JGN_TENANT_UUID=<uuid> JGN_SERO_CATEGORY_UUID=<uuid> \
 *     npx knex seed:run --specific 09_seed_jgn_serology.ts
 *
 * Also exported as seedJgnSerology(knex, opts) for direct calls.
 * Idempotent — checks (tenant_uuid, code); components by (test_item_uuid, code).
 */

type ResultType = 'single' | 'panel';

interface ComponentSeed {
	code: string;
	name: string;
	unit_of_measure: string | null;
	reference_range: string | null;
	lookup_values: string | null;
	display_order: number;
}

interface TestItemSeed {
	code: string;
	name: string;
	result_type: ResultType;
	price: number;
	method: string | null;
	unit_of_measure: string | null;
	reference_range: string | null;
	lookup_values: string | null;
	components: ComponentSeed[];
}

const ITEMS: TestItemSeed[] = [
	{
		code: 'SS008',
		name: 'Anti-HBS / HBsAb',
		result_type: 'single',
		price: 500,
		method: 'Qualitative Immunochromatographic Assay',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'SS009',
		name: 'Anti-HCV',
		result_type: 'single',
		price: 500,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST005',
		name: 'TROPONIN I',
		result_type: 'single',
		price: 500,
		method: 'Qualitative Immunochromatographic Assay',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST010',
		name: 'PROCALCITONIN',
		result_type: 'single',
		price: 1500,
		method: 'Flouresence Immuno Assay (FIA)',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST011',
		name: 'D-DIMER',
		result_type: 'single',
		price: 1500,
		method: 'Flouresence Immuno Assay (FIA)',
		unit_of_measure: 'mg/L',
		reference_range: 'less than 0.50 mg/L',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST012',
		name: 'CRP (Qualitative)',
		result_type: 'single',
		price: 500,
		method: 'Direct Agglutination',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: null,
		components: [],
	},
	{
		code: 'SS001',
		name: 'HBsAg',
		result_type: 'single',
		price: 250,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: null,
		components: [],
	},
	{
		code: 'SS002',
		name: 'Syphilis Anti-TP',
		result_type: 'single',
		price: 250,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'SS004',
		name: 'Anti-HAV IgM',
		result_type: 'single',
		price: 500,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST014',
		name: 'CARDIAC TROPONIN I (QUANTITATIVE)',
		result_type: 'single',
		price: 1000,
		method: 'FLOURESCENCE IMMUNOASSAY (FIA)',
		unit_of_measure: 'ng/mL',
		reference_range: 'less than 0.30 ng/mL',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST009',
		name: 'CRP ( Quantitative)',
		result_type: 'single',
		price: 1000,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST004',
		name: 'PSA',
		result_type: 'single',
		price: 1000,
		method: 'FLOURESCENCE IMMUNOASSAY (FIA)',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative',
		components: [],
	},
	{
		code: 'ST002',
		name: 'HbA1c',
		result_type: 'single',
		price: 850,
		method: 'FLOURESCENCE IMMUNOASSAY (FIA)',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative',
		components: [],
	},
	{
		code: 'ST015',
		name: 'DENGUE NS1, IgG, IgM',
		result_type: 'single',
		price: 1200,
		method: 'RAPID CHROMATOGRAPHIC IMMUNOASSAY',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST017',
		name: 'RPR/VDRL',
		result_type: 'single',
		price: 300,
		method: 'Direct Agglutination',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST018',
		name: 'ß HCG',
		result_type: 'single',
		price: 800,
		method: 'FLOURESCENCE IMMUNOASSAY',
		unit_of_measure: 'mIU/L',
		reference_range: '0-5.0 mIU/L',
		lookup_values: null,
		components: [],
	},
	{
		code: 'SS010',
		name: 'IONIZED CALCIUM',
		result_type: 'single',
		price: 350,
		method: 'ION SELECTIVE ELECTRODE',
		unit_of_measure: 'mmol/L',
		reference_range: '0.8-1.2 mmol/L',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST023',
		name: 'CARCINOEMBRYONIC ANTIGEN (CEA)',
		result_type: 'single',
		price: 1200,
		method: 'FLOURESCENCE IMMUNOASSAY',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST021',
		name: 'ALPHA FETOPROTEIN',
		result_type: 'single',
		price: 1000,
		method: 'Flourescence Immunoassay',
		unit_of_measure: 'ng/mL',
		reference_range: '0-20 ng/mL',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST019',
		name: 'AMYLASE',
		result_type: 'single',
		price: 500,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST020',
		name: 'LIPASE',
		result_type: 'single',
		price: 700,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'SS005',
		name: 'Salmonella typhi IgG/IgM',
		result_type: 'panel',
		price: 750,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: null,
		components: [
			{
				code: 'SS005-01',
				name: 'IgG',
				unit_of_measure: null,
				reference_range: null,
				lookup_values: 'Positive;Negative',
				display_order: 1,
			},
			{
				code: 'SS005-02',
				name: 'IgM',
				unit_of_measure: null,
				reference_range: null,
				lookup_values: 'Positive;Negative',
				display_order: 2,
			},
		],
	},
	{
		code: 'SS006',
		name: 'Dengue NS1',
		result_type: 'single',
		price: 750,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'SS003',
		name: 'Serum Pregnancy Test',
		result_type: 'single',
		price: 250,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative',
		components: [],
	},
	{
		code: 'ST001',
		name: 'TSH',
		result_type: 'single',
		price: 800,
		method: 'FLOURESCENCE IMMUNO ASSAY (FIA)',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative',
		components: [],
	},
	{
		code: 'ST006',
		name: 'T3',
		result_type: 'single',
		price: 800,
		method: 'FLOURESCENCE IMMUNOASSAY (FIA)',
		unit_of_measure: 'nmol/L',
		reference_range: '1.23-3.07 nmol/L',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST008',
		name: 'FT3',
		result_type: 'single',
		price: 900,
		method: 'FLUORESCENCE IMUUNOASSAY',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'ST003',
		name: 'fT4',
		result_type: 'single',
		price: 900,
		method: 'FLOURESCENCE IMMUNOASSAY (FIA)',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative',
		components: [],
	},
	{
		code: 'ST007',
		name: 'T4',
		result_type: 'single',
		price: 800,
		method: 'FLOURESCENCE IMMUNOASSAY (FIA)',
		unit_of_measure: 'nmol/L',
		reference_range: '66 - 181 nmol/L',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST022',
		name: 'Leptospira IgG/IgM',
		result_type: 'single',
		price: 900,
		method: 'QUALITATIVE IMMUNOCHROMATOGRAPHIC ASSAY',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
	{
		code: 'SS007',
		name: 'ASO-Titer',
		result_type: 'single',
		price: 1000,
		method: null,
		unit_of_measure: null,
		reference_range: null,
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST013',
		name: 'RHEUMATOID FACTOR (Quantitative)',
		result_type: 'single',
		price: 1000,
		method: 'Flourescence Immunoassay',
		unit_of_measure: 'IU/mL',
		reference_range: 'less than 30 IU/mL',
		lookup_values: null,
		components: [],
	},
	{
		code: 'ST016',
		name: 'HIV 1/2',
		result_type: 'single',
		price: 700,
		method: 'QUALITATIVE IMMUNOCHROMATOGRAPHIC ASSAY',
		unit_of_measure: null,
		reference_range: null,
		lookup_values: 'Positive;Negative;Reactive;Non-Reactive',
		components: [],
	},
];

export interface SeedJgnSerologyOptions {
	tenant_uuid: string;
	item_category_uuid: string;
	created_by?: string;
}

export interface SeedJgnSerologyResult {
	items_inserted: number;
	items_skipped: number;
	components_inserted: number;
}

export async function seedJgnSerology(
	knex: Knex,
	opts: SeedJgnSerologyOptions,
): Promise<SeedJgnSerologyResult> {
	const { tenant_uuid, item_category_uuid } = opts;
	const created_by = opts.created_by ?? 'seed:09_seed_jgn_serology';
	let items_inserted = 0;
	let items_skipped = 0;
	let components_inserted = 0;

	for (const item of ITEMS) {
		let row = await knex('test_items')
			.where({ tenant_uuid, code: item.code })
			.first();
		if (row) {
			items_skipped += 1;
		} else {
			const [inserted] = await knex('test_items')
				.insert({
					tenant_uuid,
					item_category_uuid,
					code: item.code,
					name: item.name,
					result_type: item.result_type,
					method: item.method,
					unit_of_measure: item.unit_of_measure,
					reference_range: item.reference_range,
					lookup_values: item.lookup_values,
					price: item.price,
					status: 'active',
					created_by,
				})
				.returning('*');
			row = inserted;
			items_inserted += 1;
		}

		if (item.result_type === 'panel' && item.components.length) {
			for (const c of item.components) {
				const exists = await knex('test_item_components')
					.where({ test_item_uuid: row.uuid, code: c.code })
					.first();
				if (exists) continue;
				await knex('test_item_components').insert({
					tenant_uuid,
					test_item_uuid: row.uuid,
					code: c.code,
					name: c.name,
					unit_of_measure: c.unit_of_measure,
					reference_range: c.reference_range,
					lookup_values: c.lookup_values,
					display_order: c.display_order,
					created_by,
				});
				components_inserted += 1;
			}
		}
	}

	return { items_inserted, items_skipped, components_inserted };
}

export async function seed(knex: Knex): Promise<void> {
	const tenant_uuid = process.env.JGN_TENANT_UUID;
	const item_category_uuid = process.env.JGN_SERO_CATEGORY_UUID;
	if (!tenant_uuid || !item_category_uuid) {
		// eslint-disable-next-line no-console
		console.warn(
			'[seed 09] Skipped — set JGN_TENANT_UUID and JGN_SERO_CATEGORY_UUID env vars, ' +
				'or import seedJgnSerology() and call it directly with your ids.',
		);
		return;
	}
	const result = await seedJgnSerology(knex, { tenant_uuid, item_category_uuid });
	// eslint-disable-next-line no-console
	console.log(
		`[seed 09] Items inserted=${result.items_inserted} skipped=${result.items_skipped}, ` +
			`components inserted=${result.components_inserted}`,
	);
}
