import type { Knex } from 'knex';

/**
 * JGN package catalog import. Sourced from jgn-items.xlsx (sheet: 'package').
 * Generated by _tmp_xlsx/build_mapping_packages.py — regenerate rather than
 * editing by hand.
 *
 * Package codes: PKG-01 … PKG-10 (zero-padded source ItemPackageID; source
 * ID 9 is intentionally skipped in the workbook, so PKG-09 is not emitted).
 *
 * Per-line new_price is a proportional split of the package total by list
 * price; rounding drift lands on the highest-priced line so
 * SUM(new_price) == package_price to the cent (matches the invariant the
 * item-package service enforces at sync time).
 *
 * Runs via env vars so the same seed can target any tenant:
 *   JGN_TENANT_UUID=<uuid> \
 *     npx knex seed:run --specific 10_seed_jgn_packages.ts
 *
 * Also exported as seedJgnPackages(knex, opts) for direct calls.
 *
 * Idempotent — packages checked by (tenant_uuid, code); package items
 * checked by (item_package_uuid, test_item_uuid). Existing rows untouched.
 * Fails loudly if any referenced test code does not exist in the tenant's
 * test_items — better to abort than silently drop a package line.
 */

interface PackageLineSeed {
	test_code: string;
	current_price: number;
	new_price: number;
	display_order: number;
}

interface PackageSeed {
	code: string;
	name: string;
	package_price: number;
	items: PackageLineSeed[];
}

const PACKAGES: PackageSeed[] = [
	{
		code: 'PKG-01',
		name: 'LAB PACKAGE - A',
		package_price: 1100,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 86.56,
				display_order: 1,
			},
			{
				test_code: 'CC003',
				current_price: 650,
				new_price: 468.84,
				display_order: 2,
			},
			{
				test_code: 'CC005',
				current_price: 150,
				new_price: 108.2,
				display_order: 3,
			},
			{
				test_code: 'CC007',
				current_price: 150,
				new_price: 108.2,
				display_order: 4,
			},
			{
				test_code: 'CC008',
				current_price: 230,
				new_price: 165.9,
				display_order: 5,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 108.2,
				display_order: 6,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 54.1,
				display_order: 7,
			},
		],
	},
	{
		code: 'PKG-02',
		name: 'LAB PACKAGE - B',
		package_price: 1300,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 87.89,
				display_order: 1,
			},
			{
				test_code: 'CC003',
				current_price: 650,
				new_price: 476.05,
				display_order: 2,
			},
			{
				test_code: 'CC005',
				current_price: 150,
				new_price: 109.86,
				display_order: 3,
			},
			{
				test_code: 'CC007',
				current_price: 150,
				new_price: 109.86,
				display_order: 4,
			},
			{
				test_code: 'CC008',
				current_price: 230,
				new_price: 168.45,
				display_order: 5,
			},
			{
				test_code: 'CC011',
				current_price: 250,
				new_price: 183.1,
				display_order: 6,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 109.86,
				display_order: 7,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 54.93,
				display_order: 8,
			},
		],
	},
	{
		code: 'PKG-03',
		name: 'LAB PACKAGE - C',
		package_price: 1500,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 88.89,
				display_order: 1,
			},
			{
				test_code: 'CC003',
				current_price: 650,
				new_price: 481.47,
				display_order: 2,
			},
			{
				test_code: 'CC005',
				current_price: 150,
				new_price: 111.11,
				display_order: 3,
			},
			{
				test_code: 'CC007',
				current_price: 150,
				new_price: 111.11,
				display_order: 4,
			},
			{
				test_code: 'CC008',
				current_price: 230,
				new_price: 170.37,
				display_order: 5,
			},
			{
				test_code: 'CC010',
				current_price: 250,
				new_price: 185.19,
				display_order: 6,
			},
			{
				test_code: 'CC011',
				current_price: 250,
				new_price: 185.19,
				display_order: 7,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 111.11,
				display_order: 8,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 55.56,
				display_order: 9,
			},
		],
	},
	{
		code: 'PKG-04',
		name: 'LAB PACKAGE - D',
		package_price: 400,
		items: [
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 126.32,
				display_order: 1,
			},
			{
				test_code: 'SS001',
				current_price: 250,
				new_price: 210.52,
				display_order: 2,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 63.16,
				display_order: 3,
			},
		],
	},
	{
		code: 'PKG-05',
		name: 'LAB PACKAGE - E',
		package_price: 525,
		items: [
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 128.05,
				display_order: 1,
			},
			{
				test_code: 'HH003',
				current_price: 140,
				new_price: 119.51,
				display_order: 2,
			},
			{
				test_code: 'SS001',
				current_price: 250,
				new_price: 213.42,
				display_order: 3,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 64.02,
				display_order: 4,
			},
		],
	},
	{
		code: 'PKG-06',
		name: 'LAB PACKAGE - F',
		package_price: 625,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 102.04,
				display_order: 1,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 127.55,
				display_order: 2,
			},
			{
				test_code: 'HH003',
				current_price: 140,
				new_price: 119.05,
				display_order: 3,
			},
			{
				test_code: 'SS001',
				current_price: 250,
				new_price: 212.58,
				display_order: 4,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 63.78,
				display_order: 5,
			},
		],
	},
	{
		code: 'PKG-07',
		name: 'LAB PACKAGE - G',
		package_price: 725,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 102.96,
				display_order: 1,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 128.7,
				display_order: 2,
			},
			{
				test_code: 'SS001',
				current_price: 250,
				new_price: 214.49,
				display_order: 3,
			},
			{
				test_code: 'SS002',
				current_price: 250,
				new_price: 214.5,
				display_order: 4,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 64.35,
				display_order: 5,
			},
		],
	},
	{
		code: 'PKG-08',
		name: 'LAB PACKAGE - H',
		package_price: 850,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 103.55,
				display_order: 1,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 129.44,
				display_order: 2,
			},
			{
				test_code: 'HH003',
				current_price: 140,
				new_price: 120.81,
				display_order: 3,
			},
			{
				test_code: 'SS001',
				current_price: 250,
				new_price: 215.74,
				display_order: 4,
			},
			{
				test_code: 'SS002',
				current_price: 250,
				new_price: 215.74,
				display_order: 5,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 64.72,
				display_order: 6,
			},
		],
	},
	{
		code: 'PKG-10',
		name: 'LAB PACKAGE - I',
		package_price: 1200,
		items: [
			{
				test_code: 'CC001',
				current_price: 120,
				new_price: 85.97,
				display_order: 1,
			},
			{
				test_code: 'CC003',
				current_price: 650,
				new_price: 465.68,
				display_order: 2,
			},
			{
				test_code: 'CC005',
				current_price: 150,
				new_price: 107.46,
				display_order: 3,
			},
			{
				test_code: 'CC007',
				current_price: 150,
				new_price: 107.46,
				display_order: 4,
			},
			{
				test_code: 'CC008',
				current_price: 230,
				new_price: 164.78,
				display_order: 5,
			},
			{
				test_code: 'HH001',
				current_price: 150,
				new_price: 107.46,
				display_order: 6,
			},
			{
				test_code: 'CM001',
				current_price: 75,
				new_price: 53.73,
				display_order: 7,
			},
			{
				test_code: 'CC006',
				current_price: 150,
				new_price: 107.46,
				display_order: 8,
			},
		],
	},
];

export interface SeedJgnPackagesOptions {
	tenant_uuid: string;
	created_by?: string;
}

export interface SeedJgnPackagesResult {
	packages_inserted: number;
	packages_skipped: number;
	lines_inserted: number;
}

export async function seedJgnPackages(
	knex: Knex,
	opts: SeedJgnPackagesOptions,
): Promise<SeedJgnPackagesResult> {
	const { tenant_uuid } = opts;
	const created_by = opts.created_by ?? 'seed:10_seed_jgn_packages';
	let packages_inserted = 0;
	let packages_skipped = 0;
	let lines_inserted = 0;

	// Resolve every referenced test code up front so we fail before writing
	// anything on a bad reference.
	const allCodes = Array.from(
		new Set(PACKAGES.flatMap((p) => p.items.map((i) => i.test_code))),
	);
	const testRows: Array<{ uuid: string; code: string }> = await knex('test_items')
		.where({ tenant_uuid })
		.whereIn('code', allCodes)
		.select('uuid', 'code');
	const testUuidByCode = new Map(testRows.map((r) => [r.code, r.uuid]));
	const missing = allCodes.filter((c) => !testUuidByCode.has(c));
	if (missing.length) {
		throw new Error(
			`[seed 10] Cannot import packages — missing test_items in tenant ${tenant_uuid}: ${missing.join(', ')}`,
		);
	}

	for (const pkg of PACKAGES) {
		let row = await knex('item_packages')
			.where({ tenant_uuid, code: pkg.code })
			.first();
		if (row) {
			packages_skipped += 1;
		} else {
			const [inserted] = await knex('item_packages')
				.insert({
					tenant_uuid,
					code: pkg.code,
					name: pkg.name,
					package_price: pkg.package_price,
					status: 'active',
					created_by,
				})
				.returning('*');
			row = inserted;
			packages_inserted += 1;
		}

		for (const line of pkg.items) {
			const test_item_uuid = testUuidByCode.get(line.test_code)!;
			const exists = await knex('item_package_items')
				.where({ item_package_uuid: row.uuid, test_item_uuid })
				.first();
			if (exists) continue;
			await knex('item_package_items').insert({
				tenant_uuid,
				item_package_uuid: row.uuid,
				test_item_uuid,
				current_price: line.current_price,
				new_price: line.new_price,
				display_order: line.display_order,
				created_by,
			});
			lines_inserted += 1;
		}
	}

	return { packages_inserted, packages_skipped, lines_inserted };
}

export async function seed(knex: Knex): Promise<void> {
	const tenant_uuid = process.env.JGN_TENANT_UUID;
	if (!tenant_uuid) {
		// eslint-disable-next-line no-console
		console.warn(
			'[seed 10] Skipped — set JGN_TENANT_UUID env var, ' +
				'or import seedJgnPackages() and call it directly with your id.',
		);
		return;
	}
	const result = await seedJgnPackages(knex, { tenant_uuid });
	// eslint-disable-next-line no-console
	console.log(
		`[seed 10] Packages inserted=${result.packages_inserted} skipped=${result.packages_skipped}, ` +
			`lines inserted=${result.lines_inserted}`,
	);
}
